Implement Async Http Client
paion-data/theresa pull request #4
Opened 2023-10-24 10:58 UTC by Xxy1016

2023-10-25 01:15 UTC, QubitPi reviewed
写一下集成测试

2023-10-25 01:15 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/web/endpoints/DataServlet.java
> +import org.asynchttpclient.*;
star imports 是要避免的

2023-10-25 10:30 UTC, QubitPi requested changes

2023-10-25 10:30 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/web/endpoints/DataServlet.java
> +        final BoundRequestBuilder postRequest = asyncHttpClient.preparePost("http://13.52.219.111:5001/invocations");
`http://13.52.219.111:5001/invocations` 放入 config class

2023-10-25 10:30 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/web/endpoints/DataServlet.java
> +    private Response httpClient(final @NotNull String data) {
- `httpClient` 放入一个单独的 class
- 测试：编写转换逻辑（单独的 class）
- Docker 测试
- @QubitPi 模拟机器学习后台服务请求

2023-10-25 10:37 UTC, QubitPi requested changes

2023-10-25 10:37 UTC, QubitPi commented on pom.xml
> +        </dependency>
dependency 的顺序是测试相关的放后面，其它放前面，这么做的原因是 maven 会先加载排在前面的 dependency，保证测试环境下的依赖配置和生产环境下的实际配置一致，async-http-client 至少放在 ` <!-- Testing —>` 之前就好

2023-10-25 13:20 UTC, QubitPi requested changes
![architecture](https://github.com/paion-data/theresa/assets/16126939/db38186c-1a6f-4cb5-9df6-ac438a3f7076)

1. 定义 `ServiceDiscovery` interface

   ```java
   public interface ServiceDiscovery {

       String getServiceUrl();
   }
   ```

3. 实现 `ServiceDiscovery` interface （`EntityExtractionServiceDiscovery.java`）

   - 使用 aeonbits owner `Config` 获取知识抽取 url：

     ```java
     public class EntityExtractionServiceDiscovery {
     
         private static final CONFIG = ConfigFactory...

         @Override
         String getServiceUrl() {
             // e.g. return “http://125.643.6.34:5001/invocations”
             return CONFIG.entityExtractionServiceUrl();
         }
     }
     ```

5. 定义 `ModelInference` interface

   ```java
   public interface ModelInference extends Function<JsonNode, JsonNode> {

       JsonNode inference(JsonNode payload);
   }
   ```

6. 实现 `ModelInference` interface (`EntityExtraction`)：将昨天的 AsyncHTTP 代码搬移到这里


   ```java
   public class EntityExtraction implements ModelInference {

       @Override
       public JsonNode inference(JsonNode payload) {
           ...
       }
   }
   ```

2023-10-26 09:02 UTC, QubitPi requested changes

2023-10-26 09:02 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/config/EntityExtractionServiceDiscoveryConfig.java
> + *          be set using {@code System.setProperty("EXAMPLE_CONFIG_KEY_NAME", "foo")}
同上

2023-10-26 09:02 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/config/EntityExtractionServiceDiscoveryConfig.java
> + *          {@code src/main/resources} source directory with contents, for example, {@code EXAMPLE_CONFIG_KEY_NAME=foo}
同上

`oauth.properties`

2023-10-26 09:02 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/inference/ModelInference.java
> + * </code>
👍🏻

2023-10-26 09:02 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/servicediscovery/EntityExtractionServiceDiscovery.java
> +    @Override
空行

2023-10-26 09:02 UTC, QubitPi commented on src/test/groovy/com/paiondata/theresa/web/endpoints/DataServletSpec.groovy
> +class DataServletSpec extends Specification {
暂时关闭这个测试

2023-10-26 09:02 UTC, QubitPi commented on src/test/groovy/com/paiondata/theresa/web/endpoints/DataServletSpec.groovy
> +        System.setProperty("ENTITY_EXTRACTION_SERVICE_URL", "http://13.52.219.111:5001/invocations")
隐藏url

2023-10-26 09:23 UTC, Xxy1016 commented on .github/workflows/ci-cd.yml
> +  USER: Xxy1016
名字写错了改了一下

2023-10-26 09:57 UTC, QubitPi commented on .github/workflows/ci-cd.yml
> +  USER: Xxy1016
ok

2023-10-26 09:57 UTC, QubitPi commented on src/test/java/com/paiondata/theresa/JettyServerFactory.java
> +        Objects.requireNonNull(resourceConfig, "resourceConfig null");
JDK 17 对 NULL 检查做了优化，这两行代码可以删掉了

2023-10-26 09:57 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/web/endpoints/DataServlet.java
> +        this.entityExtraction = Objects.requireNonNull(entityExtraction);
JDK 17 对 NULL 检查做了优化，可以直接写 `this.entityExtraction = entityExtraction`

2023-10-26 09:57 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/inference/EntityExtraction.java
> +        this.serviceDiscovery = Objects.requireNonNull(serviceDiscovery);
JDK 17 对 NULL 检查做了优化，可以直接写 this.serviceDiscovery = serviceDiscovery

2023-10-26 09:57 UTC, QubitPi commented on src/main/java/com/paiondata/theresa/inference/EntityExtraction.java
> +        final AsyncHttpClient asyncHttpClient = asyncHttpClient();
asyncHttpClient 很耗资源，写成 instance variable

2023-10-26 10:17 UTC, QubitPi approved these changes

2023-10-26 10:19 UTC, merged